### ISSUE TITLE
Option to skip pit filling

### ISSUE THREAD

**Issue by bwj202** [waternumbers/dynatopGIS#39]
Often it is unnecessary to fill pits in a elevation surface, either because it has already been done or if it is necessary to retain pits in the surface; the latter being more likely to break things, so focusing on the former.
In our case we have already made changes to our elevation surface to ensure hydrological connectivity using an optimised filling tool rather than a standard fill and would like to skip the pit filling step in dynatopGIS in order to avoid undoing the conditioning we have already done. 

I think the workflow would benefit from a switch to skip the pit filling step.

**Comment by waternumbers** [comment]
You can skip the sink filling by setting the max_it option in the call to the sink fill method to 0. This should avoid any sink filling but produce the expected output files.

However the underlying principle in the model (as of <v0.3.*) is that the topography dictates the flow direction, as such if you have a depression that is not part of the channel network it is possible that surface water would collect there and not flow out (since adjacent cells are higher). In practice you shouldn't get this far since you will encounter other errors saying not all the hillslope areas are connected to the channel and/or catchment outlet(s) when building the model.

If you want to use depressions that are apparently unconnected to the channel network your best plan (until a more complete hydraulic surface representation is available) is to connect them by creating "notional" channels, then parametrise the storage volume using a [compound channel](https://waternumbers.github.io/dynatop/articles/HRU.html#compound-channels)

**Comment by bwj202** [comment]
OK that makes sense, thanks.
